### ISSUE TITLE
keras error after installation

### ISSUE THREAD

**Issue by sleepryansleep** [MiraldiLab/maxATAC#122]
Hi, I run the following commands and am receiving this error (at the end). Please let me know if you have any ideas (I'm also working with our IT people to see if the issue is on our end somewhere.) Thank you!
```

[s161282@Nucleus005 ~]$ conda create -n maxatac -c bioconda python=3.9 samtools wget bedtools ucsc-bedgraphtobigwig pigz
Collecting package metadata (current_repodata.json): | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:[https://conda.anaconda.org:443](https://conda.anaconda.org/) "GET /bioconda/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:[https://conda.anaconda.org:443](https://conda.anaconda.org/) "GET /bioconda/linux-64/current_repodata.json HTTP/1.1" 304 0                                   / DEBUG:urllib3.connectionpool:[https://repo.anaconda.com:443](https://repo.anaconda.com/) "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:[https://repo.anaconda.com:443](https://repo.anaconda.com/) "GET /pkgs/main/linux-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:[https://repo.anaconda.com:443](https://repo.anaconda.com/) "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:[https://repo.anaconda.com:443](https://repo.anaconda.com/) "GET /pkgs/r/linux-64/current_repodata.json HTTP/1.1" 304 0                                      done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.7.2
  latest version: 23.7.3

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.3



## Package Plan ##

  environment location: /home2/s161282/.conda/envs/maxatac

  added / updated specs:
    - bedtools
    - pigz
    - python=3.9
    - samtools
    - ucsc-bedgraphtobigwig
    - wget


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  bedtools           bioconda/linux-64::bedtools-2.26.0-0
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  c-ares             pkgs/main/linux-64::c-ares-1.19.0-h5eee18b_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2023.05.30-h06a4308_0
  curl               pkgs/main/linux-64::curl-8.1.1-h37d81fd_2
  krb5               pkgs/main/linux-64::krb5-1.20.1-h568e23c_1
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1
  libcurl            pkgs/main/linux-64::libcurl-8.1.1-h91b91d3_2
  libedit            pkgs/main/linux-64::libedit-3.1.20221030-h5eee18b_0
  libev              pkgs/main/linux-64::libev-4.33-h7f8727e_1
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_0
  libgcc             pkgs/main/linux-64::libgcc-7.2.0-h69d50b8_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libidn2            pkgs/main/linux-64::libidn2-2.3.4-h5eee18b_0
  libnghttp2         pkgs/main/linux-64::libnghttp2-1.52.0-ha637b67_1
  libpng             pkgs/main/linux-64::libpng-1.6.39-h5eee18b_0
  libssh2            pkgs/main/linux-64::libssh2-1.10.0-h37d81fd_2
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  libunistring       pkgs/main/linux-64::libunistring-0.9.10-h27cfd23_0
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0
  mysql-connector-c  bioconda/linux-64::mysql-connector-c-6.1.6-2
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0
  openssl            pkgs/main/linux-64::openssl-1.1.1v-h7f8727e_0
  pigz               pkgs/main/linux-64::pigz-2.6-h27cfd23_0
  pip                pkgs/main/linux-64::pip-23.2.1-py39h06a4308_0
  python             pkgs/main/linux-64::python-3.9.17-h7a1cb2a_0
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0
  samtools           bioconda/linux-64::samtools-1.5-1
  setuptools         pkgs/main/linux-64::setuptools-68.0.0-py39h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.41.2-h5eee18b_0
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0
  ucsc-bedgraphtobi~ bioconda/linux-64::ucsc-bedgraphtobigwig-357-0
  wget               pkgs/main/linux-64::wget-1.21.4-h91b91d3_1
  wheel              pkgs/main/linux-64::wheel-0.38.4-py39h06a4308_0
  xz                 pkgs/main/linux-64::xz-5.4.2-h5eee18b_0
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_0


Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate maxatac
#
# To deactivate an active environment, use
#
#     $ conda deactivate

[s161282@Nucleus005 ~]$
[s161282@Nucleus005 ~]$ conda activate maxatac
(maxatac) [s161282@Nucleus005 ~]$ pip install maxatac
Collecting maxatac
  Using cached maxatac-1.0.5.tar.gz (60 kB)
  Preparing metadata (setup.py) ... done
Collecting tensorflow (from maxatac)
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/d6/af/cb5ea6d1a9c83e715e29b45a598ebf542729cd216b43f5deefc27657bd38/tensorflow-2.13.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading tensorflow-2.13.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting tensorboard (from maxatac)
  Obtaining dependency information for tensorboard from https://files.pythonhosted.org/packages/bc/a2/ff5f4c299eb37c95299a76015da3f30211468e29d8d6f1d011683279baee/tensorboard-2.14.0-py3-none-any.whl.metadata
  Using cached tensorboard-2.14.0-py3-none-any.whl.metadata (1.8 kB)
Collecting biopython (from maxatac)
  Downloading biopython-1.81-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 29.5 MB/s eta 0:00:00
Requirement already satisfied: py2bit in ./.local/lib/python3.9/site-packages (from maxatac) (0.3.0)
Requirement already satisfied: pyBigWig in ./.local/lib/python3.9/site-packages (from maxatac) (0.3.17)
Collecting pydot (from maxatac)
  Using cached pydot-1.4.2-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: matplotlib in ./.local/lib/python3.9/site-packages (from maxatac) (3.3.3)
Collecting scikit-learn (from maxatac)
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/d4/61/966d3238f6cbcbb13350d31bd0accfc5efdf9e349cd2a42d9761b8b67a18/scikit_learn-1.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading scikit_learn-1.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: pybedtools in ./.local/lib/python3.9/site-packages (from maxatac) (0.8.1)
Requirement already satisfied: pandas in ./.local/lib/python3.9/site-packages (from maxatac) (1.1.4)
Collecting pyfiglet (from maxatac)
  Using cached pyfiglet-0.8.post1-py2.py3-none-any.whl (865 kB)
Requirement already satisfied: pyyaml in ./.local/lib/python3.9/site-packages (from maxatac) (5.3.1)
Requirement already satisfied: pysam in ./.local/lib/python3.9/site-packages (from maxatac) (0.16.0.1)
Requirement already satisfied: seaborn in ./.local/lib/python3.9/site-packages (from maxatac) (0.11.0)
Collecting numpy (from biopython->maxatac)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/69/1f/c95b1108a9972a52d7b1b63ed8ca70466b59b8c1811bd121f1e667cc45d8/numpy-1.25.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading numpy-1.25.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.9/site-packages (from matplotlib->maxatac) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.9/site-packages (from matplotlib->maxatac) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in ./.local/lib/python3.9/site-packages (from matplotlib->maxatac) (8.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./.local/lib/python3.9/site-packages (from matplotlib->maxatac) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in ./.local/lib/python3.9/site-packages (from matplotlib->maxatac) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in ./.local/lib/python3.9/site-packages (from pandas->maxatac) (2020.4)
Requirement already satisfied: six in ./.local/lib/python3.9/site-packages (from pybedtools->maxatac) (1.15.0)
Requirement already satisfied: scipy>=1.5.0 in ./.local/lib/python3.9/site-packages (from scikit-learn->maxatac) (1.5.4)
Collecting joblib>=1.1.1 (from scikit-learn->maxatac)
  Obtaining dependency information for joblib>=1.1.1 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn->maxatac)
  Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metadata
  Downloading threadpoolctl-3.2.0-py3-none-any.whl.metadata (10.0 kB)
Collecting absl-py>=0.4 (from tensorboard->maxatac)
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
Collecting grpcio>=1.48.2 (from tensorboard->maxatac)
  Obtaining dependency information for grpcio>=1.48.2 from https://files.pythonhosted.org/packages/69/67/46ce6471c94af40118d728caa7e840fd55c70878dcfdad9837003e5863b6/grpcio-1.57.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading grpcio-1.57.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting google-auth<3,>=1.6.3 (from tensorboard->maxatac)
  Obtaining dependency information for google-auth<3,>=1.6.3 from https://files.pythonhosted.org/packages/9c/8d/bff87fc722553a5691d8514da5523c23547f3894189ba03b57592e37bdc2/google_auth-2.22.0-py2.py3-none-any.whl.metadata
  Using cached google_auth-2.22.0-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard->maxatac)
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Collecting markdown>=2.6.8 (from tensorboard->maxatac)
  Obtaining dependency information for markdown>=2.6.8 from https://files.pythonhosted.org/packages/1a/b5/228c1cdcfe138f1a8e01ab1b54284c8b83735476cb22b6ba251656ed13ad/Markdown-3.4.4-py3-none-any.whl.metadata
  Downloading Markdown-3.4.4-py3-none-any.whl.metadata (6.9 kB)
Collecting protobuf>=3.19.6 (from tensorboard->maxatac)
  Obtaining dependency information for protobuf>=3.19.6 from https://files.pythonhosted.org/packages/f3/d8/fb02c40aa129c385430d177e4d9fa0160cb89be29305c8760861e538a2e4/protobuf-4.24.2-cp37-abi3-manylinux2014_x86_64.whl.metadata
  Using cached protobuf-4.24.2-cp37-abi3-manylinux2014_x86_64.whl.metadata (540 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in ./.local/lib/python3.9/site-packages (from tensorboard->maxatac) (2.25.0)
Requirement already satisfied: setuptools>=41.0.0 in ./.conda/envs/maxatac/lib/python3.9/site-packages (from tensorboard->maxatac) (68.0.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard->maxatac)
  Obtaining dependency information for tensorboard-data-server<0.8.0,>=0.7.0 from https://files.pythonhosted.org/packages/02/52/fb9e51fba47951aabd7a6b25e41d73eae94208ccf62d886168096941a781/tensorboard_data_server-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata
  Using cached tensorboard_data_server-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in ./.local/lib/python3.9/site-packages (from tensorboard->maxatac) (1.0.1)
Requirement already satisfied: wheel>=0.26 in ./.conda/envs/maxatac/lib/python3.9/site-packages (from tensorboard->maxatac) (0.38.4)
Collecting astunparse>=1.6.0 (from tensorflow->maxatac)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers>=23.1.21 (from tensorflow->maxatac)
  Obtaining dependency information for flatbuffers>=23.1.21 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
Collecting gast<=0.4.0,>=0.2.1 (from tensorflow->maxatac)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting google-pasta>=0.1.1 (from tensorflow->maxatac)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Requirement already satisfied: h5py>=2.9.0 in ./.local/lib/python3.9/site-packages (from tensorflow->maxatac) (3.1.0)
Collecting keras<2.14,>=2.13.1 (from tensorflow->maxatac)
  Obtaining dependency information for keras<2.14,>=2.13.1 from https://files.pythonhosted.org/packages/2e/f3/19da7511b45e80216cbbd9467137b2d28919c58ba1ccb971435cb631e470/keras-2.13.1-py3-none-any.whl.metadata
  Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
Collecting libclang>=13.0.0 (from tensorflow->maxatac)
  Obtaining dependency information for libclang>=13.0.0 from https://files.pythonhosted.org/packages/ea/df/55525e489c43f9dbb6c8ea27d8a567b3dcd18a22f3c45483055f5ca6611d/libclang-16.0.6-py2.py3-none-manylinux2010_x86_64.whl.metadata
  Using cached libclang-16.0.6-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Collecting numpy (from biopython->maxatac)
  Downloading numpy-1.24.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 65.2 MB/s eta 0:00:00
Collecting opt-einsum>=2.3.2 (from tensorflow->maxatac)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Requirement already satisfied: packaging in ./.local/lib/python3.9/site-packages (from tensorflow->maxatac) (20.4)
Collecting tensorboard (from maxatac)
  Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow->maxatac)
  Obtaining dependency information for tensorflow-estimator<2.14,>=2.13.0 from https://files.pythonhosted.org/packages/72/5c/c318268d96791c6222ad7df1651bbd1b2409139afeb6f468c0f327177016/tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata
  Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting termcolor>=1.1.0 (from tensorflow->maxatac)
  Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Requirement already satisfied: typing-extensions<4.6.0,>=3.6.6 in ./.local/lib/python3.9/site-packages (from tensorflow->maxatac) (3.7.4.3)
Requirement already satisfied: wrapt>=1.11.0 in ./.local/lib/python3.9/site-packages (from tensorflow->maxatac) (1.12.1)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow->maxatac)
  Obtaining dependency information for tensorflow-io-gcs-filesystem>=0.23.1 from https://files.pythonhosted.org/packages/14/44/8e501aa789e96f64653ff5be1f110174ed4162c44b2a9f372fcd9e08899c/tensorflow_io_gcs_filesystem-0.33.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata
  Downloading tensorflow_io_gcs_filesystem-0.33.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
Collecting cachetools<6.0,>=2.0.0 (from google-auth<3,>=1.6.3->tensorboard->maxatac)
  Obtaining dependency information for cachetools<6.0,>=2.0.0 from https://files.pythonhosted.org/packages/a9/c9/c8a7710f2cedcb1db9224fdd4d8307c9e48cbddc46c18b515fefc0f1abbe/cachetools-5.3.1-py3-none-any.whl.metadata
  Using cached cachetools-5.3.1-py3-none-any.whl.metadata (5.2 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3,>=1.6.3->tensorboard->maxatac)
  Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.3/181.3 kB 21.4 MB/s eta 0:00:00
Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard->maxatac)
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Requirement already satisfied: urllib3<2.0 in ./.local/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard->maxatac) (1.26.2)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<1.1,>=0.5->tensorboard->maxatac)
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting importlib-metadata>=4.4 (from markdown>=2.6.8->tensorboard->maxatac)
  Obtaining dependency information for importlib-metadata>=4.4 from https://files.pythonhosted.org/packages/cc/37/db7ba97e676af155f5fcb1a35466f446eadc9104e25b83366e8088c9c926/importlib_metadata-6.8.0-py3-none-any.whl.metadata
  Downloading importlib_metadata-6.8.0-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: chardet<4,>=3.0.2 in ./.local/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard->maxatac) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in ./.local/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard->maxatac) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard->maxatac) (2020.11.8)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.9/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard->maxatac) (3.4.0)
Collecting pyasn1<0.6.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->maxatac)
  Downloading pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.9/83.9 kB 2.8 MB/s eta 0:00:00
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard->maxatac)
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Downloading scikit_learn-1.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 19.1 MB/s eta 0:00:00
Downloading tensorflow-2.13.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.1/524.1 MB 3.6 MB/s eta 0:00:00
Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Using cached google_auth-2.22.0-py2.py3-none-any.whl (181 kB)
Downloading grpcio-1.57.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 37.1 MB/s eta 0:00:00
Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 32.4 MB/s eta 0:00:00
Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
Using cached libclang-16.0.6-py2.py3-none-manylinux2010_x86_64.whl (22.9 MB)
Downloading Markdown-3.4.4-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.2/94.2 kB 12.8 MB/s eta 0:00:00
Using cached protobuf-4.24.2-cp37-abi3-manylinux2014_x86_64.whl (311 kB)
Using cached tensorboard_data_server-0.7.1-py3-none-manylinux2014_x86_64.whl (6.6 MB)
Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
Downloading tensorflow_io_gcs_filesystem-0.33.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 39.7 MB/s eta 0:00:00
Downloading threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Using cached cachetools-5.3.1-py3-none-any.whl (9.3 kB)
Downloading importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Building wheels for collected packages: maxatac
  Building wheel for maxatac (setup.py) ... done
  Created wheel for maxatac: filename=maxatac-1.0.5-py3-none-any.whl size=67428 sha256=2d7ddaba5367bd3b22e1b0af8fff140885609188e4edae5731c4e62bc6beae84
  Stored in directory: /home2/s161282/.cache/pip/wheels/21/75/e8/d85361c202c9dc24cf0f5af4170b351c666f875df2d52103a9
Successfully built maxatac
Installing collected packages: pyfiglet, libclang, flatbuffers, threadpoolctl, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, pydot, pyasn1, protobuf, oauthlib, numpy, keras, joblib, importlib-metadata, grpcio, google-pasta, gast, cachetools, astunparse, absl-py, rsa, requests-oauthlib, pyasn1-modules, opt-einsum, markdown, biopython, scikit-learn, google-auth, google-auth-oauthlib, tensorboard, tensorflow, maxatac
  Attempting uninstall: joblib
    Found existing installation: joblib 0.17.0
    Uninstalling joblib-0.17.0:
      Successfully uninstalled joblib-0.17.0
Successfully installed absl-py-1.4.0 astunparse-1.6.3 biopython-1.81 cachetools-5.3.1 flatbuffers-23.5.26 gast-0.4.0 google-auth-2.22.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 grpcio-1.57.0 importlib-metadata-6.8.0 joblib-1.3.2 keras-2.13.1 libclang-16.0.6 markdown-3.4.4 maxatac-1.0.5 numpy-1.24.3 oauthlib-3.2.2 opt-einsum-3.3.0 protobuf-4.24.2 pyasn1-0.5.0 pyasn1-modules-0.3.0 pydot-1.4.2 pyfiglet-0.8.post1 requests-oauthlib-1.3.1 rsa-4.9 scikit-learn-1.3.0 tensorboard-2.13.0 tensorboard-data-server-0.7.1 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.33.0 termcolor-2.3.0 threadpoolctl-3.2.0
(maxatac) [s161282@Nucleus005 ~]$ maxatac -h
Traceback (most recent call last):
  File "/home2/s161282/.conda/envs/maxatac/bin/maxatac", line 7, in <module>
    from maxatac.utilities.parser import parse_arguments, print_args
  File "/home2/s161282/.conda/envs/maxatac/lib/python3.9/site-packages/maxatac/utilities/parser.py", line 17, in <module>
    from maxatac.analyses.train import run_training
  File "/home2/s161282/.conda/envs/maxatac/lib/python3.9/site-packages/maxatac/analyses/train.py", line 5, in <module>
    from keras.utils.data_utils import OrderedEnqueuer
ModuleNotFoundError: No module named 'keras.utils.data_utils'
```

**Comment by sleepryansleep** [comment]
Nvm, we fixed by changing the version of python we installed with. c:

**Comment by bjstewart1** [comment]
> Nvm, we fixed by changing the version of python we installed with. c:

what was the fix? I am dealing with the same issue
