### ISSUE TITLE
Error on running prepare: subprocess.CalledProcessError

### ISSUE THREAD

**Issue by Lozzard** [MiraldiLab/maxATAC#128]
Hi!
I am trying to run maxatac preapre but it fails with finding the file “ATAC_bowtie2_pipeline.sh” I guess. Did I miss some necessary process? Here is the output for reference.

maxatac prepare -i IMR90_rep1_atac.bam -o ./output -prefix IMR90_rep1_atac
[2024-02-01 16:40:23,160]
Prepare Parameters:
Input file: IMR90_rep1_atac.bam
Limiting to chromosomes: ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22']
Input chromosome sizes file: /root/opt/maxatac/data/hg38/hg38.chrom.sizes
Tn5 cut sites will be slopped 20 bps on each side
Input blacklist file: /root/opt/maxatac/data/hg38/hg38_maxatac_blacklist.bw
Output filename: IMR90_rep1_atac
Output directory: ./output
Using a millions factor of: 20000000
Using 9 threads to run job.
[2024-02-01 16:40:23,162]
Generate the normalized signal tracks.
[2024-02-01 16:40:23,162]
Working on a bulk ATAC-seq BAM file
Getting the number of reads in the BAM file
There are 60310654 reads in the file
[2024-02-01 16:42:34,410]
Processing BAM to bigwig. Running eduplication
bash: /root/opt/maxatac/data/scripts/ATAC/ATAC_bowtie2_pipeline.sh: No such file or directory
Traceback (most recent call last):
  File "/root/anaconda3/envs/maxatac/bin/maxatac", line 24, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/root/anaconda3/envs/maxatac/bin/maxatac", line 20, in main
    args.func(args)
  File "/root/anaconda3/envs/maxatac/lib/python3.9/site-packages/maxatac/analyses/prepare.py", line 87, in run_prepare
    subprocess.run(["bash",
  File "/root/anaconda3/envs/maxatac/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '/root/opt/maxatac/data/scripts/ATAC/ATAC_bowtie2_pipeline.sh', 'IMR90_rep1_atac.bam', 'IMR90_rep1_atac', '/mnt/e/CTCF/CTCF feature/output', '9', '/root/opt/maxatac/data/hg38/hg38_maxatac_blacklist.bed', '/root/opt/maxatac/data/hg38/hg38.chrom.sizes', '20', '0.33161636748293266', 'deduplicate', 'chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22']' returned non-zero exit status 127.

**Comment by Lozzard** [comment]
Sorry, I missed the downloading required reference data step
